language: python
python:
  - "3.6"
# command to install dependencies
install:
    - sudo apt-get install chromium-chromedriver
    - pip install -r requirements.txt nose flake8
before_script:
    - flake8 --ignore=E501 mintapi # pep8 flake ignoring long lines
# command to run tests
script: nosetests
